name: 'git-ftp-deploy'
author: 'Komsan Nurak <git-ftp-action@stackcodecode.com>'
description: 'Uses git-ftp and GitHub actions to deploy a GitHub repository to a FTP server.'
inputs:
  url:
    description: 'URL'
    required: true
  user:
    description: 'FTP login name'
    required: true
  password:
    description: 'FTP password'
    required: true
  syncroot:
    description: 'Specifies a local directory to sync from as if it were the git project root path.'
    required: false
    default: '.'
  options:
    description: 'Additional options'
    required: false
    default: '--auto-init'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'blue'
  icon: 'upload-cloud'
